# threshold difference in percents (0.1 = 10%)
threshold: 0.1

# scheduler for reading logs and send metrics to prometheus
scheduler:
  fixed-rate: 15000 # 15 * 1000 ~ 15 seconds
  delay: 0
 
# path for log (metrics) from NGINX/HAProxy module
metrics:
  filepath: /usr/local/nginx/logs/metrics.log

# actuator settings
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
